### PR TITLE
Change steamos to holoiso

### PR DESCRIPTION
**Pull request by yarik303**
at moment you cant install steam os anywhere but holoiso is  a project that makes it possible

### CODE REVIEW

**Comment by KripC2160** [comment]
Wow I didn't expect this project to still have some activities! 😅 I am totally up for the changes here. I am still conflicted about adding the BSD distros in here, since there are not_technically_linux. I can change the project name to **Find Me a Unix Distro** if your up for it and in that case BSD would be welcome.

**Comment by KripC2160** [comment]
Oh I checked and see that the fork has a name change of 'FMAD'. I think that can work as well. I'll try to get the conflicts resolved and change the projects name 👍

**Comment by KripC2160** [comment]
The changes have been made, hopefully no issues are left now. Thanks for keeping the project alive :) If you want @MiguelCarino I will add a link to your repository on the readme.md to redirect from my repo to yours, since are the one carrying this project forward

**Comment by MiguelCarino** [comment]
@KripC2160 Thanks! Sorry for the late response, I just noticed notifications because I'm used to never have any. As for the name, I didn't really added 'UNIX' because I'm interested on finding all kinds of operating systems.

**Pull request merged**
