### PR TITLE
I forked it and did the following changes, so please take what you want from the following:

### PR DESCRIPTION
**Pull request by MiguelCarino**
Fixed links for amogos and crunchbangplusplus
"https://amogos.studio/",
"https://www.crunchbangplusplus.org/",
I added Ultramarine to redhatlinks
"https://ultramarine-linux.org",
Changed RHEL link to
"https://developers.redhat.com/products/rhel/download",
Added cutefish to debianlinks (also changed debainlinks into debianlinks)
"https://en.cutefishos.com/",
Moved ututo and justbrowsing into EOLlinks (last releases are from 2017 and 2014)
"http://www.ututo.org/en/",
"http://justbrowsinglinux.com/",
Moved ubuntuce out of EOL links (last release is based in Ubuntu 22.04)
"http://ubuntuce.com/",
Added asahi, breath, and bsd variants to otherlinks (I understand BSD )
"https://asahilinux.org/",
"https://cb-linux.github.io/breath/",
"https://www.ghostbsd.org/",
"https://www.freebsd.org/",
"https://www.openbsd.org/",
"https://www.netbsd.org/",
"https://www.dragonflybsd.org/",
"https://www.midnightbsd.org/",
"https://nomadbsd.org/",
"https://hellosystem.github.io/",

### CODE REVIEW

**Review by KripC2160 — APPROVED** [review]
thanks for the changes

**Review by KripC2160 — CHANGES_REQUESTED** [review]
I understand BSD however I did not include it since it is not totally linux. I used to have bunch of them before the first launch but decided to remove them. Is it possible to remove them?

**Comment by MiguelCarino** [comment]
I did remove them through another commit.

**Comment by KripC2160** [comment]
Alright it looks good now thanks for the commit

**Comment by KripC2160** [comment]
Oh also the official domain is now down so it is on my pages so it will take a bit of time to get the uodates up (its late at night here)

**Pull request merged**
